### PR TITLE
fix(chrome): find map services without broad host permissions

### PR DESCRIPTION
**Pull request by giswqs**
## Summary

- The Chrome extension requested `http://*/*` and `https://*/*` so its background service worker could watch map requests with `webRequest`. The Chrome Web Store flags that as a broad host permission and routes the submission to an in-depth review. The popup now reads each frame's Resource Timing buffer under `activeTab` when the user clicks the icon, so the manifest is down to `activeTab` and `scripting`, with no service worker, no storage, and no standing access to any site.
- MapLibre and similar renderers fetch vector tiles from a web worker, whose requests never reach the document's timing buffer. Such a tileset is recovered instead from the metadata the main thread does fetch: its TileJSON, or failing that its style document. `serviceUrlParameter` now accepts an `add=ogc-vector-tiles` link carrying only `serviceStyle`, since GeoLibre resolves the tiles and source layers from that document.
- Deletes `background.mjs` along with the per-tab task queue and navigation-generation bookkeeping that existed only to keep one page's in-flight requests out of the next page's list. A timing buffer belongs to its own document, so that problem no longer arises.

## Test plan

- [x] `npm run test:frontend` (6371 pass, 0 fail); 70 pass across `tests/chrome-extension.test.ts` and `tests/data-url.test.ts`
- [x] `pre-commit run --files <changed>` clean, including the npm build
- [x] Playwright against live third-party maps: OpenLayers tiled WMS detects `ahocevar.com/geoserver/wms` layer `topp:states`, OpenLayers WMTS detects the USGS GetTile template with layer `sgmc2`, and the iframed MapLibre example detects `demotiles.maplibre.org/tiles/tiles.json` paired with its `style.json`
- [x] Both deep-link shapes open the prefilled Add Data dialog against a production build and add a vector tile layer that draws
- [ ] Load the unpacked extension in Chrome and walk the sample table in `extensions/geolibre-chrome/README.md`
- [ ] Upload `dist/geolibre-chrome-0.3.0.zip` and confirm the dashboard no longer shows the broad host permissions warning

## Known limits

The Resource Timing buffer holds 250 entries per document and stops recording once full, so a very busy page can lose a service added late. Raising that needs a `document_start` script, which needs back the host permissions this change removes, so the cap is accepted and documented.

## Summary by CodeRabbit

- **New Features**
  - Improved map-service detection, including vector-tile TileJSON and style URLs.
  - Discover services from requests made by the current page and embedded frames.
  - Improved support for style-only vector-tile links.

- **Bug Fixes**
  - Removed redundant service URL parameters when style and service URLs match.
  - Improved vector-tile service pairing and deduplication.

- **Documentation**
  - Clarified click-to-inspect behavior, permissions, privacy, limitations, and usage examples.
  - Documented that the extension does not monitor activity in the background or store detected URLs.

### CODE REVIEW

File: extensions/geolibre-chrome/service-scanner.mjs [hunk 1]
```diff
@@ -247,108 +256,52 @@ export function mergeServiceCandidates(...groups) {
...
+    merged.push({
+      url: styleUrl,
+      name: "Vector tile style",
+      format: "Vector tiles",
+      kind: "vector",
+      styleUrl,
+      layer: null,
+    });
+  }
+  return merged.slice(0, MAX_SERVICE_CANDIDATES);
```
[the remark this answers is not in the document]
Comment (giswqs) [reply extensions/geolibre-chrome/service-scanner.mjs]: Done in 510520ff — the cap is now taken out of the ordinary services first: `room = MAX_SERVICE_CANDIDATES - fallbacks.length`, so the style fallbacks always get their slots. A page varied enough to reach 100 is mostly repeating layers of a few endpoints, while a fallback is the only trace its origin leaves at all. Covered by a new test that fills the cap with 150 WMS layers plus one style and asserts the style survives.

File: extensions/geolibre-chrome/service-scanner.mjs [hunk 2]
```diff
@@ -178,6 +178,15 @@ export function classifyServiceRequest(rawUrl) {
...
   }
 
+  // A MapLibre-style renderer fetches its `.pbf` tiles from a web worker, and a
+  // worker's requests are recorded in the worker's own timeline rather than the
+  // document's, so the TileJSON the main thread fetched to find them can be the
+  // only trace of the tileset. The body is never read, so a TileJSON describing
+  // raster tiles is indistinguishable here and is offered as a vector tileset.
+  if (/\/tile(?:s|json)\.json$/i.test(path)) {
+    return candidate(url, "Vector tiles", "vector", "Vector tile service");
+  }
```
[the remark this answers is not in the document]
Comment (giswqs) [reply extensions/geolibre-chrome/service-scanner.mjs]: Done in 510520ff — the pattern is now `/tile(?:s?|json)\.json$/i`, so `tile.json`, `tiles.json`, and `tilejson.json` all match. A regression test asserts discovery for all three spellings.

File: extensions/geolibre-chrome/service-scanner.mjs [hunk 3]
```diff
@@ -178,6 +178,15 @@ export function classifyServiceRequest(rawUrl) {
     return candidate(url, "OGC API", "vector", "OGC API service", api.href);
   }
 
+  // A MapLibre-style renderer fetches its `.pbf` tiles from a web worker, and a
+  // worker's requests are recorded in the worker's own timeline rather than the
+  // document's, so the TileJSON the main thread fetched to find them can be the
+  // only trace of the tileset. The body is never read, so a TileJSON describing
+  // raster tiles is indistinguishable here and is offered as a vector tileset.
+  if (/\/tile(?:s|json)\.json$/i.test(path)) {
```
[the remark this answers is not in the document]
Comment (giswqs) [reply extensions/geolibre-chrome/service-scanner.mjs]: Partly addressed in 510520ff. The singular `tile.json` now matches alongside `tiles.json` and `tilejson.json`. Broader sniffing is not safe: a server-generated name like tileserver-gl's `/data/<id>.json` is not distinguishable from any other JSON request by URL alone, and promoting arbitrary `.json` would offer half a page's API calls as tilesets. That case is not lost, though: tileserver-gl serves `/styles/<id>/style.json`, which the style classifier matches, so the tileset is reached through the style fallback instead. The README now states the sniff's limits explicitly rather than leaving 'recovered from its TileJSON' to imply full coverage.

File: extensions/geolibre-chrome/service-scanner.mjs (hunk 2 above)
[the remark this answers is not in the document]
Comment (giswqs) [reply extensions/geolibre-chrome/service-scanner.mjs:188]: Leaving this one open for a human call, because the suggested fix is not reachable from this design.

Establishing that a TileJSON is vector means reading its body, which means fetching a cross-origin URL. The extension holds no host permissions after this PR (removing them is the entire point: the store was routing the submission to in-depth review), and `fetch` from the popup to an arbitrary origin needs exactly the permission that was dropped. So there is no 'verify then promote' path here.

That leaves omitting the fallback, which costs more than it saves. Worker-fetched vector tilesets are otherwise undetectable, and that includes MapLibre, so omitting it would give up the main capability this PR adds in order to avoid a mislabel.

The failure mode when the guess is wrong is bounded and visible: a raster TileJSON opens the Add Data dialog, `resolveOgcVectorTiles` finds no source layers, and the dialog reports that and refuses to submit. Nothing renders incorrectly and no request is made on the user's behalf. This is documented at the branch in `service-scanner.mjs` and, as of 510520ff, in the README.

Happy to drop the fallback if the maintainer would rather have no false positives than worker-tileset support.

File: extensions/geolibre-chrome/service-scanner.mjs [hunk 4]
```diff
@@ -247,108 +256,58 @@ export function mergeServiceCandidates(...groups) {
...
+    if (covered) continue;
+    fallbacks.push({
+      url: styleUrl,
+      name: "Vector tile style",
+      format: "Vector tiles",
+      kind: "vector",
+      styleUrl,
+      layer: null,
+    });
+  }
```
[the remark this answers is not in the document]
Comment (giswqs) [reply extensions/geolibre-chrome/service-scanner.mjs:316]: Good catch, fixed in 65552354. A style now becomes a candidate of its own only when its path names it a map style: `…/style.json`, `…/styles.json`, or an ArcGIS `…/resources/styles/<name>.json`. The looser `…/styles/<name>.json` was the collision you describe, so a style matched that way keeps its old, low-stakes role of explaining a tileset already found at its origin and is never promoted on its own. `GET /styles/dark.json` on a page with no tileset now yields nothing. Verified against the live MapLibre example, which serves `/style.json` and is still detected. Two tests cover it: the theme route enriches but does not stand alone, and the ArcGIS style does stand alone.

File: extensions/geolibre-chrome/README.md [hunk 5]
```diff
@@ -49,10 +49,39 @@ virtualized, canonicalizes links to `data.source.coop`, and removes duplicate
...
+  can resolve a layer from on its own. A style is only offered in its own right
+  when no tileset from its origin was found.
+
+  A TileJSON is recognized by name (`tile.json`, `tiles.json`, `tilejson.json`),
+  which is narrower than every way a server can name one: tileserver-gl serves
+  `/data/<id>.json`, and that tileset is reached through its style rather than
+  its metadata. Nothing reads the response, so a TileJSON describing *raster*
+  tiles is indistinguishable from a vector one and is offered as a vector
+  tileset; selecting it opens the dialog on a document with no source layers,
+  which reports that plainly rather than drawing the wrong thing. Reading the
```
[the remark this answers is not in the document]
Comment (giswqs) [reply extensions/geolibre-chrome/README.md]: Done in 65552354 — reworded to say that Add Data resolves the document on submit and refuses it when no source layers come out, instead of implying every selection opens on an empty dialog.

File: packages/plugins/src/plugins/maplibre-raster.ts [hunk 6]
```diff
@@ -450,6 +450,18 @@ export interface RasterVisualizationDefaults {
...
+// public plugin-API surface, so it must not make `maplibre-gl-raster`'s types a
+// hard dependency of every external plugin. Nothing otherwise links the two, and
+// a renamed or dropped identifier would reach `control.setEngine()` as a string
+// the control no longer knows, with no build error. These assert both directions
+// so a bump of `maplibre-gl-raster` fails `npm run typecheck` instead.
+type Mirrors<Mirror extends Source, Source> = never;
+export type CogRenderEngineMirrorIsExact = [
+  Mirrors<GeoLibreCogRenderEngine, RasterRenderEngine>,
+  Mirrors<RasterRenderEngine, GeoLibreCogRenderEngine>,
+];
```
[the remark this answers is not in the document]
Comment (giswqs) [reply packages/plugins/src/plugins/maplibre-raster.ts:463]: Correct, and it is not mine to remove: 6b7da56f was committed directly to this branch by the maintainer while it was checked out, not authored as part of the extension change. Leaving this thread open so they can decide whether to split it out; I have not touched that commit.

File: extensions/geolibre-chrome/service-scanner.mjs [hunk 7]
```diff
@@ -247,108 +259,59 @@ export function mergeServiceCandidates(...groups) {
...
-    forget(tabId) {
-      tabs.delete(tabId);
-    },
-  };
+export function collectServiceCandidates(urls) {
+  const stylesByOrigin = new Map();
+  const services = [];
+  for (const url of urls) {
+    const style = classifyStyleRequest(url);
+    if (style) stylesByOrigin.set(style.origin, style);
```
[the remark this answers is not in the document]
Comment (giswqs) [reply extensions/geolibre-chrome/service-scanner.mjs]: Correct, and a real bug I introduced in 65552354. Fixed in 4d085f22 with the same precedence you propose, written as `if (style && (!stylesByOrigin.get(style.origin)?.named || style.named))`: a named style is never displaced by a generic one, a named style still replaces an earlier named one, and generic-over-generic keeps the previous last-wins behavior. Test covers both request orders, for the style-alone case and the tileset-pairing case, and it fails against the pre-fix code.

[the remark this answers is not in the document]
Comment (giswqs) [reply extensions/geolibre-chrome/service-scanner.mjs]: Confirmed and fixed in 4d085f22 — your trace is exactly right, including the second consequence of an already-found tileset being paired with the theme document. The precedence now keeps a named style over a later generic one from the same origin. I checked the new test fails against the pre-fix code before committing it, so the regression is pinned rather than assumed.

File: packages/plugins/src/plugins/maplibre-raster.ts (hunk 6 above)
[the remark this answers is not in the document]
Comment (giswqs) [reply packages/plugins/src/plugins/maplibre-raster.ts:463]: Scope note stands and is the maintainer's call: 6b7da56f was committed straight to this branch while it was checked out, not authored as part of the extension change. Leaving this open for them; I have not touched that commit.

On the second half, I did check rather than eyeball it. Dropping `titiler` from `GeoLibreCogRenderEngine` fails the build with `maplibre-raster.ts(462,11): error TS2344: Type 'RenderEngine' does not satisfy the constraint 'GeoLibreCogRenderEngine'`, and adding a member the real union lacks fails the other assertion at line 461 (plus a knock-on error in usePlugins.ts). Both directions are enforced. types.ts was restored afterwards; neither experiment is in the branch.

File: extensions/geolibre-chrome/popup.mjs [hunk 8]
```diff
@@ -144,9 +144,19 @@ async function inspectPage() {
...
-  renderDatasets(mergeServiceCandidates(documentDatasets, stored[key] ?? []));
+  let services = [];
+  try {
+    // A map can be embedded in a frame, and the requests are recorded by the
+    // document that made them, so every frame is asked for its own history.
+    const results = await chrome.scripting.executeScript({
+      target: { tabId: tab.id, allFrames: true },
+      func: collectRequestedUrls,
+    });
+    services = collectServiceCandidates(results.flatMap((frame) => frame?.result ?? []));
```
[the remark this answers is not in the document]
Comment (giswqs) [reply extensions/geolibre-chrome/popup.mjs:161]: Good catch — you were right to push on this, and the verification did not hold up.

`activeTab` grants host permission for the tab's **main frame origin** only, and Chrome deliberately does not extend that grant to a frame from another origin, so `allFrames: true` reaches the top frame and its same-origin frames and nothing else.

The reason the live test looked like it proved otherwise: the MapLibre docs page embeds its example with `<iframe src="../display-a-map.html">` — a relative URL, so that iframe is **same-origin** with maplibre.org. The test exercised the reachable case and never a genuinely cross-origin frame, while the README generalized it to "services a page reaches only through an embedded frame".

Fixed in 645fa0bd as documentation rather than code, since reaching a cross-origin frame needs the standing host permission this PR exists to remove:
- a third bullet in the buffer-consequences list spelling out the boundary,
- narrowed the two summary sentences ("each reachable frame", "every same-origin frame below it"),
- relabeled the table row "in a same-origin `iframe`" and said why that example qualifies,
- a comment next to the `allFrames` call in popup.mjs.

On the swallowed-error worry: `executeScript` skips frames it lacks access to rather than rejecting the whole call, so the reachable frames still return their buffers and the `catch` is not hiding a per-frame refusal. A map living wholly in a cross-origin frame now simply reports no services — which is the documented behavior instead of an unstated gap.

File: packages/plugins/src/plugins/maplibre-raster.ts (hunk 6 above)
[the remark this answers is not in the document]
Comment (giswqs) [reply packages/plugins/src/plugins/maplibre-raster.ts:463]: Two parts here — provenance and the compiler check.

**Provenance:** this was not an accidental carry-over. The mirror landed in 6b7da56f, whose message is literally "Address Claude review feedback" — an earlier round of this same review bot on this same PR asked for it. So it is intentional, though it is fair to say it grew out of review rather than the original scope.

**The `Mirrors<Mirror extends Source, Source>` trick:** you were right not to take it on inspection, so I tested it rather than reasoning about it. Editing `GeoLibreCogRenderEngine` in `packages/plugins/src/types.ts` and running `tsc` gives errors in both directions:

Dropping `"titiler"` (mirror narrower than source) fails the *second* assertion:
```
packages/plugins/src/plugins/maplibre-raster.ts(462,11): error TS2344:
  Type 'RenderEngine' does not satisfy the constraint 'GeoLibreCogRenderEngine'.
  Type '"titiler"' is not assignable to type 'GeoLibreCogRenderEngine'.
```

Adding a bogus `"bogus-engine"` (mirror wider than source) fails the *first*:
```
packages/plugins/src/plugins/maplibre-raster.ts(461,11): error TS2344:
  Type 'GeoLibreCogRenderEngine' does not satisfy the constraint 'RenderEngine'.
```

Both members restored afterwards; the working tree is clean. So the forward-referencing constraint does enforce both directions as documented — a renamed or dropped engine identifier fails the build rather than reaching `control.setEngine()` as a string the control no longer knows.

Whether to still split it into its own PR is @giswqs's call, but it is neither broken nor accidental.

[the remark this answers is not in the document]
Comment (giswqs) [reply packages/plugins/src/plugins/maplibre-raster.ts:463]: Confirming it was intentional rather than a stray rebase: the mirror landed in 6b7da56f, a commit titled "Address Claude review feedback" — an earlier round of this same review bot on this PR asked for it. It grew out of review on this branch rather than arriving from elsewhere.

I also verified it actually enforces what it claims, since the bidirectional `extends` trick is unusual enough not to take on inspection. Dropping `"titiler"` from `GeoLibreCogRenderEngine` fails `tsc` at maplibre-raster.ts(462,11), and adding a bogus member fails at (461,11) — both directions, as documented. Details in the reply on the other thread covering this same line.

Whether to still split it into its own PR for a cleaner revert trail is @giswqs's call; flagging it was reasonable.

File: CLAUDE.md [hunk 9]
```diff
@@ -132,6 +132,7 @@ The browser build proxies the sidecar at `/sidecar` (same-origin, no CORS); conf
...
+- `GeoLibreCogRenderEngine` (`packages/plugins/src/types.ts`) mirrors the `RenderEngine` union `maplibre-gl-raster` exports (`maplibre-gl-raster` | `cog-tiler-wasm` | `titiler`). It is hand-written rather than imported because `types.ts` is the public plugin-API surface and importing there would make that package's types a hard dependency of every external plugin. Unlike the mirrors above this one is checked by the **compiler**, not a test: `CogRenderEngineMirrorIsExact` in `packages/plugins/src/plugins/maplibre-raster.ts` asserts both directions of assignability against the real imported type, so a renamed or dropped engine identifier fails `npm run typecheck`. Nothing extra to do on a `maplibre-gl-raster` bump beyond letting the build run; without it a stale identifier would reach `control.setEngine()` as a string the control no longer recognizes, silently leaving the raster unrendered.
```
[the remark this answers is not in the document]
Comment (giswqs) [reply CLAUDE.md:135]: Not an accidental pickup from a rebase: this CLAUDE.md entry and the matching `CogRenderEngineMirrorIsExact` assertion landed together in 6b7da56f, a commit titled "Address Claude review feedback" — an earlier round of this same review bot on this PR asked for them.

The entry's claim that drift fails `npm run typecheck` is verified, not just asserted: dropping `"titiler"` from `GeoLibreCogRenderEngine` fails `tsc` at maplibre-raster.ts(462,11), and adding a bogus member fails at (461,11).

Whether to split it out so the Chrome-extension change stays independently revertable is @giswqs's call.
